import ScrollRestorationController from "@/controllers/ScrollRestorationController";
import ColorSchemeController from "@/controllers/ColorSchemeController";
import { StateProvider } from "@/context/StateContext";
import "./globals.css";

import { getSiteData } from "@/lib/fetch";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const [site] = await Promise.all([getSiteData()]);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, invert = false }) {
  return (
    <html lang="en">
      <StateProvider>
        <body>
          <Header />
          {children}
          <Footer site={site} />
        </body>
      </StateProvider>
      <ScrollRestorationController />
      <ColorSchemeController />
    </html>
  );
}
